config/routes.rb
Rails.application.routes.draw do
  resources :turf_details
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/turf_detail.rb
class TurfDetail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def index

  end

end

app/controllers/turf_details_controller.rb
class TurfDetailsController < ApplicationController
  before_action :set_turf_detail, only: [:show, :edit, :update, :destroy]

  # GET /turf_details
  # GET /turf_details.json
  def index
    @turf_details = TurfDetail.all
  end

  # GET /turf_details/1
  # GET /turf_details/1.json
  def show
  end

  # GET /turf_details/new
  def new
    @turf_detail = TurfDetail.new
  end

  # GET /turf_details/1/edit
  def edit
  end

  # POST /turf_details
  # POST /turf_details.json
  def create
    @turf_detail = TurfDetail.new(turf_detail_params)

    respond_to do |format|
      if @turf_detail.save
        format.html { redirect_to @turf_detail, notice: 'Turf detail was successfully created.' }
        format.json { render :show, status: :created, location: @turf_detail }
      else
        format.html { render :new }
        format.json { render json: @turf_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turf_details/1
  # PATCH/PUT /turf_details/1.json
  def update
    respond_to do |format|
      if @turf_detail.update(turf_detail_params)
        format.html { redirect_to @turf_detail, notice: 'Turf detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @turf_detail }
      else
        format.html { render :edit }
        format.json { render json: @turf_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turf_details/1
  # DELETE /turf_details/1.json
  def destroy
    @turf_detail.destroy
    respond_to do |format|
      format.html { redirect_to turf_details_url, notice: 'Turf detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turf_detail
      @turf_detail = TurfDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turf_detail_params
      params.require(:turf_detail).permit(:title, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/turf_details_helper.rb
module TurfDetailsHelper
end

app/views/homes/index.html.erb
<h1>vikas</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TBooking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/turf_details/_form.html.erb
<%= form_with(model: turf_detail, local: true) do |form| %>
  <% if turf_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turf_detail.errors.count, "error") %> prohibited this turf_detail from being saved:</h2>

      <ul>
      <% turf_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turf_details/edit.html.erb
<h1>Editing Turf Detail</h1>

<%= render 'form', turf_detail: @turf_detail %>

<%= link_to 'Show', @turf_detail %> |
<%= link_to 'Back', turf_details_path %>

app/views/turf_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turf Details</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turf_details.each do |turf_detail| %>
      <tr>
        <td><%= turf_detail.title %></td>
        <td><%= turf_detail.address %></td>
        <td><%= link_to 'Show', turf_detail %></td>
        <td><%= link_to 'Edit', edit_turf_detail_path(turf_detail) %></td>
        <td><%= link_to 'Destroy', turf_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turf Detail', new_turf_detail_path %>

app/views/turf_details/new.html.erb
<h1>New Turf Detail</h1>

<%= render 'form', turf_detail: @turf_detail %>

<%= link_to 'Back', turf_details_path %>

app/views/turf_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @turf_detail.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @turf_detail.address %>
</p>

<%= link_to 'Edit', edit_turf_detail_path(@turf_detail) %> |
<%= link_to 'Back', turf_details_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>